export const RouterPath = {
  root: '/',
  main: '/',
  notFound: '*',
  challenge: 'challenge',
  inProgress: 'in-progress',
  myRecord: 'done',
  record: 'record',
  detail: 'detail',
  shorts: 'shorts',
  rank: 'rank',
  dashboard: 'dashboard',
  login: 'login',
  redirect: 'redirect',
  auth: 'auth',
  register: 'register',
  review: 'review',
  write: 'write',
  challengeList: 'list',
};
